export { default as Navbar } from "../../../components/Navs/Navbar";
export { default as Footer } from "../../../components/Navs/Footer";
export { default as Banner } from "../../../components/Banners/Banner";
export { default as Cover } from "../../../components/Cards/GamePrices/Cover";
export { default as Marketplaces } from "../../../components/Cards/Maps/Shop/Marktplaces";
export { default as Official } from "../../../components/Cards/Maps/Shop/Official";
export { default as Keysellers } from "../../../components/Cards/Maps/Shop/Keysellers";
export { default as HistoryPrices } from "../../../components/Cards/GamePrices/HistoryPrices";
export { default as Infos } from "../../../components/Cards/GamePrices/Infos";
